// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // livestreaming: [{ type: "autogenerated", dirName: "." }],

  livestreaming: [
    {
      type: "html",
      value: "Getting Started",
      className: "sidebar-heading",
      defaultStyle: true,
    },
    "index",
    { type: "autogenerated", dirName: "getting-started" },

    {
      type: "html",
      value: "Workflow Guides",
      className: "sidebar-heading",
      defaultStyle: true,
    },
    { type: "autogenerated", dirName: "workflows" },

    {
      type: "html",
      value: "Location Guides",
      className: "sidebar-heading",
      defaultStyle: true,
    },
    { type: "autogenerated", dirName: "locations" },

    {
      type: "html",
      value: "Reference",
      className: "sidebar-heading",
      defaultStyle: true,
    },
    { type: "autogenerated", dirName: "reference" },
  ],
};

export default sidebars;
