// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // livestreaming: [{ type: "autogenerated", dirName: "." }],

  livestreaming: [
    {
      type: "html",
      value: "Getting Started",
      className: "sidebar-heading",
      defaultStyle: true,
    },
    "livestreaming/index",
    { type: "autogenerated", dirName: "livestreaming/getting-started" },

    {
      type: "html",
      value: "Workflow Guides",
      className: "sidebar-heading",
      defaultStyle: true,
    },
    { type: "autogenerated", dirName: "livestreaming/workflows" },

    {
      type: "html",
      value: "Location Guides",
      className: "sidebar-heading",
      defaultStyle: true,
    },
    { type: "autogenerated", dirName: "livestreaming/locations" },

    {
      type: "html",
      value: "Reference",
      className: "sidebar-heading",
      defaultStyle: true,
    },
    { type: "autogenerated", dirName: "livestreaming/reference" },
  ],
  assets: [
    "assets/index",
    {
      type: "html",
      value: "Organizations",
      className: "sidebar-heading",
      defaultStyle: true,
    },
    {
      type: "category",
      label: "LSMSA Film Club",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "assets/film" }],
    },
    {
      type: "category",
      label: "LSMSA Athletics",
      link: {
        type: "generated-index",
      },
      items: [{ type: "autogenerated", dirName: "assets/athletics" }],
    },
    // {
    //   type: "category",
    //   label: "Assets",
    //   items: [{ type: "autogenerated", dirName: "assets" }],
    // },
  ],
};

export default sidebars;
